import read from "read-file-utf8";
import write from "write-file-utf8";

const metadata = await read("src/metadata.json");
const colors = await read("src/styles/colors.json");

const { themeColor } = colors;

const content = (entryPoint) => `<!DOCTYPE html>
<!-- ------------------------------------------------------------------

    DO NOT EDIT THIS FILE!

    it is generated by

        npm run build_html

------------------------------------------------------------------- -->
<html lang="en" className="has-navbar-fixed-top">
  <head>
    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="${themeColor}">

    <link rel="apple-touch-icon" href="/logo192.png">

    <title>${metadata.asciiName}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <script type="module" src="/src/polyfills.ts"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${entryPoint}"></script>
  </body>
</html>
`;

await write("index.html", content("/src/main.tsx"));
